version: "3.3"

networks:
  app-tier:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - app-tier
  rabbitmq:
    image: "bitnami/rabbitmq:3.8"
    container_name: rabbitmq
    environment: 
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"
    networks:
      - app-tier
volumes:
  rabbitmq_data:
    driver: local
