version: '3.3'

services:
  postgres:
    image: bitnami/postgresql
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_USER: postgres    
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data: