version: "3.3"

networks:
  app-tier:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
  rabbitmqstats_data:
    driver: local
  rabbitmqdisc1_data:
    driver: local
  rabbitmqram1_data:
    driver: local

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - app-tier
  stats:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=${RABBITMQ_ERL_COOKIE}
    ports:
      - '15672:15672'
    volumes:
      - 'rabbitmqstats_data:/bitnami'
    networks:
      - app-tier
  queue-disc1:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbit@queue-disc1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=${RABBITMQ_ERL_COOKIE}
    volumes:
      - 'rabbitmqdisc1_data:/bitnami'
    networks:
      - app-tier
  queue-ram1:
    image: bitnami/rabbitmq
    environment:
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_NODE_TYPE=queue-ram
      - RABBITMQ_NODE_NAME=rabbit@queue-ram1
      - RABBITMQ_CLUSTER_NODE_NAME=rabbit@stats
      - RABBITMQ_ERL_COOKIE=${RABBITMQ_ERL_COOKIE}
    volumes:
      - 'rabbitmqram1_data:/bitnami'
    networks:
      - app-tier