version: "2"
services:
  webtop:
    image: linuxserver/webtop:ubuntu-mate
    container_name: webtop
    restart: unless-stopped
    environment:
      - TZ=America/Chicago
      - PUID=1000
      - PGID=1000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Docker Socket on the system, if you want to use Docker in the container
      - /host/path/to/config:/config # Application home directory
    ports:
      - 3000:3000/tcp # Web Desktop GUI
    shm_size: "2gb"
