version: "3.8"

services:
  db:
    build: 
      context: ./db
      args:
        - name=value
        - PASSWORD=${PASSWORD}
    image: db
    container_name: db    
    ports:
      - "1433:1433"
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${PASSWORD}
    ports:
      - "1433:1433"
    command: |
      """
      # ./opt/mssql-tools/bin/sqlcmd -U sa -P ${PASSWORD} -i /usr/src/app/init.sql
      # /opt/mssql/bin/sqlservr
      """
    volumes:
      - "./init.sql:/usr/src/app/init.sql"
    healthcheck:
      test:
        [
          "CMD",
          "/opt/mssql-tools/bin/sqlcmd",
          "-U",
          "sa",
          "-P",
          "${PASSWORD}",
          "-Q",
          "SELECT @@VERSION"
        ]
      interval: 1s
      timeout: 10s
      retries: 20
      start_period: 40s
  flyway:
    image: flyway/flyway
    container_name: flyway
    command: -user=sa -password=${PASSWORD} -connectRetries=3 migrate
    volumes:
      - "./conf:/flyway/conf"
      - "./sql:/flyway/sql"
    depends_on:
      - sqlserver