version: "3.3"

networks:
  app-tier:
    driver: bridge

volumes:
  sqlserver_data:
    driver: local
  rabbitmq_data:
    driver: local

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQLSERVER_SA_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - app-tier
  rabbitmq:
    image: "bitnami/rabbitmq"
    container_name: rabbitmq
    environment: 
      - RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
    ports:
      - "4369:4369"
      - "5672:5672"
      - "25672:25672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/bitnami"
    networks:
      - app-tier