version: '3.3'

services:
  db:
    image: bitnami/postgresql
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${PASSWORD}
    ports:
      - 5432:5432
    restart: always